### ISSUE TITLE
Bug on commands

### ISSUE THREAD

**Issue by Keanottesen** [stitchng/adonis-bugsnag#6]
## Issue
When I am using the package to report bugs, it works fine on any given bug related to my HTTP endpoint. However, if I have an command running in a job or something similar it does not report any bug to bugsnag.

## Package version
"adonisjs-bugsnag": "^0.2.0",

## Node.js and npm version
NODE: 12.17.0
NPM: 6.14.8

## Sample Code (to reproduce the issue)
Make a command and create an error. The bug will not be posted to bugsnag.

**Comment by stitchng** [comment]
@Keanottesen , We will look into this soon. So very sorry for the late reply.

**Comment by isocroft** [comment]
@Keanottesen you concern will be fixed (alongside many other improvements) in the next release ( **v0.2.1** ) for this package 📦 coming on the 15th of December, 2021. Thank you 🙏 

Also, something you could try right now is to directly call the `notify()` method in the area of the codebase logic where you are running the job like so:

```js
'use strict';

const bugsnag = use('BugSnag')

try {
   await runningJob();
} catch (error) {
   bugsnag.notify(error, { url: () => '' })
}   
```

I believe it should help.... Please do let me know
